version: "3"

services:
  next:
    image: node:18-alpine
    ports:
      - "${NEXT_PORT}:3000"
    volumes:
      - ./next:/home/node/app
      - next_node_modules:/home/node/app/node_modules
    working_dir: /home/node/app
    command: sh -c "npm install && npm run dev"
    networks:
      backend:

  storybook:
    image: node:18-alpine
    ports:
      - "${STORYBOOK_PORT}:6006"
    volumes:
      - ./next:/home/node/app
      - storybook_node_modules:/home/node/app/node_modules
    working_dir: /home/node/app
    depends_on:
      - next
    command: sh -c "npm install && npm run storybook"

  payload:
    image: node:18-alpine
    ports:
      - "${PAYLOAD_PORT}:3000"
    volumes:
      - ./payload:/home/node/app
      - payload_node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/payload
      PORT: ${PAYLOAD_PORT}
      NODE_ENV: development
      PAYLOAD_SECRET: TESTING
      PAYLOAD_URL: ${PAYLOAD_URL}
    networks:
      backend:

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none
    networks:
      backend:

volumes:
  data:
  payload_node_modules:
  next_node_modules:
  storybook_node_modules:

networks:
  backend:
